version: '3.1'
services:
  reader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reader #容器名 可自行修改
    restart: always
    ports:
      - "4396:8080"   # 4396 端口映射可自行修改,8080请勿修改
    volumes:
      - ./storage:/storage #数据映射目录 /home/reader/storage 映射目录可自行修改
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      #- READER_APP_USERLIMIT=50 #用户上限,默认且最大值为50
      - READER_APP_USERBOOKLIMIT=200 #用户书籍上限,默认200
      - READER_APP_CACHECHAPTERCONTENT=true #开启缓存章节内容
      # - READER_APP_REMOTEWEBVIEWAPI=http://readerwebview:8050 #启用webview(若下方readerwebview容器不开启需注释此行
      # ↓多用户模式配置↓
      - READER_APP_SECURE=true #开启登录鉴权，开启后将支持多用户模式
      - READER_APP_SECUREKEY=adminpwd  #管理员密码  建议修改
      - READER_APP_INVITECODE=registercode #注册邀请码 建议修改,如不需要可注释或删除
volumes:
  reader:
  readerwebview: